package main.proyecto.integrador.Presentacion;
import javax.swing.*;
import java.awt.*; // Aseg
import main.proyecto.integrador.Logica.validarDatos;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author genny
 */
public class Login extends javax.swing.JFrame {
    // Instanciar la clase ValidarDatos (fuera del método del botón, como un atributo de la clase de tu formulario)
     private validarDatos validador = new validarDatos();
    /**
     * Creates new form Login
     */
    public Login() {
 
        
        initComponents();

        // Panel con degradado
        DegradadoPanel panelDegradado = new DegradadoPanel();
        panelDegradado.setBounds(panelLogin.getBounds()); // Asegura el tamaño y posición del panel
        this.remove(panelLogin); // Eliminar el panel anterior
        this.add(panelDegradado); // Añadir el panel degradado

        // Crear el panel circular
        PanelCircular panelCircular = new PanelCircular(30); // Radio de esquinas
        panelCircular.setBounds(panelEncima.getBounds()); // Copiar posición y tamaño
        panelCircular.setBackground(Color.WHITE); // Color de fondo

        // Quitar el panelEncima original
        this.remove(panelEncima); // Remover el panel existente
        // Agregar el panel circular al formulario
        this.add(panelCircular); // Añadir el nuevo panel

        // Agregar el segundo panel encima del degradado
        panelDegradado.setLayout(null); // Deshabilitar layout para control manual
        panelDegradado.add(panelCircular); // Añadir el nuevo panel
        panelCircular.setLayout(null); // Deshabilitar layout para control manual
         
        // Agregar componentes al panel circular
        panelCircular.add(lLogin);
        panelCircular.add(lIcono);
        panelCircular.add(lUser);
        panelCircular.add(tUser);
        panelCircular.add(lpassword);
        panelCircular.add(tPassword);
        panelCircular.add(bLogin);
        
        // Centrar la ventana
        setLocationRelativeTo(null);

        // Repaint y revalidate para actualizar la UI
        this.repaint();
        this.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        panelEncima = new javax.swing.JPanel();
        lUser = new javax.swing.JLabel();
        lpassword = new javax.swing.JLabel();
        tUser = new javax.swing.JTextField();
        lLogin = new javax.swing.JLabel();
        bLogin = new javax.swing.JButton();
        lIcono = new javax.swing.JLabel();
        tPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLogin.setPreferredSize(new java.awt.Dimension(400, 430));

        panelEncima.setBackground(new java.awt.Color(255, 255, 255));
        panelEncima.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 51), null));

        lUser.setForeground(new java.awt.Color(0, 51, 102));
        lUser.setText("Nombre de usuario");

        lpassword.setBackground(new java.awt.Color(255, 255, 255));
        lpassword.setForeground(new java.awt.Color(0, 51, 102));
        lpassword.setText("Contraseña");

        tUser.setForeground(new java.awt.Color(0, 0, 51));

        lLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lLogin.setText("Iniciar sesión");

        bLogin.setBackground(new java.awt.Color(0, 153, 153));
        bLogin.setForeground(new java.awt.Color(255, 255, 255));
        bLogin.setText("Iniciar sesión ");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        lIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/proyecto/integrador/images/file.jpg"))); // NOI18N

        javax.swing.GroupLayout panelEncimaLayout = new javax.swing.GroupLayout(panelEncima);
        panelEncima.setLayout(panelEncimaLayout);
        panelEncimaLayout.setHorizontalGroup(
            panelEncimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEncimaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(panelEncimaLayout.createSequentialGroup()
                .addGroup(panelEncimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEncimaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelEncimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lUser, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tUser, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(tPassword)))
                    .addGroup(panelEncimaLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(bLogin))
                    .addGroup(panelEncimaLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lIcono)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelEncimaLayout.setVerticalGroup(
            panelEncimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncimaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lpassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bLogin)
                .addGap(40, 40, 40))
        );

        tUser.getAccessibleContext().setAccessibleName("Nombre usuario");

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(panelEncima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(panelEncima, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
        String username = tUser.getText().trim();
        String password = new String(tPassword.getPassword()).trim();
        

        if (validador.validarUsuario(username, password)) { // Usa el método validarUsuario
            String rol = validador.validarRol(username);
            Principal pr = new Principal(rol); // Cambia a la ventana principal
            pr.setVisible(true);
            this.dispose(); // Cierra la ventana de login
        } else {
            if (validador.intentos ==5){
                bLogin.setEnabled(false); // Deshabilitar el botón de login
                JOptionPane.showMessageDialog(this, "Ha alcanzado el máximo número de intentos permitidos. Intente más tarde.");
                System.exit(0);
            }
            JOptionPane.showMessageDialog(this, "Usuario o contraseña inválidos.");
            tUser.setText("");
            tPassword.setText("");     
        }
    }//GEN-LAST:event_bLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(() -> {
            Login login = new Login();
            login.setVisible(true); // Muestra la ventana de login
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JLabel lIcono;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lUser;
    private javax.swing.JLabel lpassword;
    private javax.swing.JPanel panelEncima;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUser;
    // End of variables declaration//GEN-END:variables
}
